name: CI

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
